spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


server:
  port: 8080
  servlet:
    context-path: /app/


#  spring.datasource.url=jdbc:mysql://localhost:3306/user_management
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.username=root
#  spring.datasource.password=12345
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#  spring.jpa.hibernate.ddl-auto=update
#
#  server.port=9090
#  server.servlet.context-path=/app
