spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


server:
  port: 8080
  servlet:
    context-path: /app/
